specVersion: 0.2.0
name: test
version: 0.0.1
description: 'subquery-web3games'
repository: ''
schema:
  file: ./schema.graphql
network:
  endpoint: wss://devnet.web3games.org/
  genesisHash: '0x024bf352d2ff26bf351b389ce7239a8484ab3318f63bf4a460abe1ec6ef87ab7'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlockInfo
          kind: substrate/BlockHandler
        - handler: handleExtrinsic
          kind: substrate/CallHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleAccountTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleNewAccountCreate
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Endowed
        - handler: handleAccountBalance
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleTokenFungibleCreate
          kind: substrate/EventHandler
          filter:
            module: tokenFungible
            method: TokenCreated
        - handler: handleTokenNonFungibleCreate
          kind: substrate/EventHandler
          filter:
            module: tokenNonFungible
            method: TokenCreated
        - handler: handleEvmInfo
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: transact