specVersion: 0.2.0
name: test
version: 0.0.1
description: 'subquery-web3games'
repository: ''
schema:
  file: ./schema.graphql
network:
  endpoint: wss://testnet.web3games.org/
  genesisHash: '0x456938824b0bb8c1e171c10cb6b84243d01573c5b48821d4e9b29e935fd01bf8'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlockInfo
          kind: substrate/BlockHandler
        - handler: handleExtrinsic
          kind: substrate/CallHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleAccountTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleNewAccountCreate
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Endowed
        - handler: handleAccountBalance
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleTokenFungibleCreate
          kind: substrate/EventHandler
          filter:
            module: tokenFungible
            method: TokenCreated
        - handler: handleTokenNonFungibleCreate
          kind: substrate/EventHandler
          filter:
            module: tokenNonFungible
            method: TokenCreated
